# @Author: Rafael Direito
# @Date:   2022-10-05 18:25:06 (WEST)
# @Email:  rdireito@av.it.pt
# @Copyright: Insituto de Telecomunicações - Aveiro, Aveiro, Portugal
# @Last Modified by:   Rafael Direito
# @Last Modified time: 2022-10-05 18:26:15 (WEST)

version: "3.8"
services:
  rabbitmq3:
    container_name: "cameras-container"
    env_file:
      - camera/.env
    args:
    RABBIT_MQ_USERNAME: ${RABBIT_MQ_USERNAME}
    RABBIT_MQ_PASSWORD: ${RABBIT_MQ_PASSWORD}
    RABBIT_MQ_URL: ${RABBIT_MQ_URL}
    RABBIT_MQ_EXCHANGE_NAME: ${RABBIT_MQ_EXCHANGE_NAME}
    RABBIT_MQ_QUEUE_NAME: ${RABBIT_MQ_QUEUE_NAME}
